package entity;
// Generated 27-05-2017 13:33:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comuna generated by hbm2java
 */
public class Comuna  implements java.io.Serializable {


     private int idComuna;
     private Region region;
     private String comunaNombre;
     private Set usuarios = new HashSet(0);

    public Comuna() {
    }

	
    public Comuna(int idComuna, Region region, String comunaNombre) {
        this.idComuna = idComuna;
        this.region = region;
        this.comunaNombre = comunaNombre;
    }
    public Comuna(int idComuna, Region region, String comunaNombre, Set usuarios) {
       this.idComuna = idComuna;
       this.region = region;
       this.comunaNombre = comunaNombre;
       this.usuarios = usuarios;
    }
   
    public int getIdComuna() {
        return this.idComuna;
    }
    
    public void setIdComuna(int idComuna) {
        this.idComuna = idComuna;
    }
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    public String getComunaNombre() {
        return this.comunaNombre;
    }
    
    public void setComunaNombre(String comunaNombre) {
        this.comunaNombre = comunaNombre;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


