package entity;
// Generated 27-05-2017 13:33:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Documento generated by hbm2java
 */
public class Documento  implements java.io.Serializable {


     private int idDocumento;
     private Edicion edicion;
     private Editorial editorial;
     private Tipo tipo;
     private Autor autor;
     private Categoria categoria;
     private String titulo;
     private Date anoPublicacion;
     private Set ejemplars = new HashSet(0);

	public Documento(){}
     
    public Documento(Edicion edicion, Editorial editorial, Tipo tipo, Autor autor, Categoria categoria, String titulo, Date anoPublicacion) {
        this.edicion = edicion;
        this.editorial = editorial;
        this.tipo = tipo;
        this.autor = autor;
        this.categoria = categoria;
        this.titulo = titulo;
        this.anoPublicacion = anoPublicacion;
    }
    public Documento(int idDocumento, Edicion edicion, Editorial editorial, Tipo tipo, Autor autor, Categoria categoria, String titulo, Date anoPublicacion, Set ejemplars) {
       this.idDocumento = idDocumento;
       this.edicion = edicion;
       this.editorial = editorial;
       this.tipo = tipo;
       this.autor = autor;
       this.categoria = categoria;
       this.titulo = titulo;
       this.anoPublicacion = anoPublicacion;
       this.ejemplars = ejemplars;
    }
   
    public int getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(int idDocumento) {
        this.idDocumento = idDocumento;
    }
    public Edicion getEdicion() {
        return this.edicion;
    }
    
    public void setEdicion(Edicion edicion) {
        this.edicion = edicion;
    }
    public Editorial getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(Editorial editorial) {
        this.editorial = editorial;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public Autor getAutor() {
        return this.autor;
    }
    
    public void setAutor(Autor autor) {
        this.autor = autor;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getAnoPublicacion() {
        return this.anoPublicacion;
    }
    
    public void setAnoPublicacion(Date anoPublicacion) {
        this.anoPublicacion = anoPublicacion;
    }
    public Set getEjemplars() {
        return this.ejemplars;
    }
    
    public void setEjemplars(Set ejemplars) {
        this.ejemplars = ejemplars;
    }




}


