package entity;
// Generated 27-05-2017 13:33:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Edicion generated by hbm2java
 */
public class Edicion  implements java.io.Serializable {


     private int idEdicion;
     private String nroEdicion;
     private Set documentos = new HashSet(0);

    public Edicion() {
    }

	
    public Edicion(int idEdicion, String nroEdicion) {
        this.idEdicion = idEdicion;
        this.nroEdicion = nroEdicion;
    }
    public Edicion(int idEdicion, String nroEdicion, Set documentos) {
       this.idEdicion = idEdicion;
       this.nroEdicion = nroEdicion;
       this.documentos = documentos;
    }
   
    public int getIdEdicion() {
        return this.idEdicion;
    }
    
    public void setIdEdicion(int idEdicion) {
        this.idEdicion = idEdicion;
    }
    public String getNroEdicion() {
        return this.nroEdicion;
    }
    
    public void setNroEdicion(String nroEdicion) {
        this.nroEdicion = nroEdicion;
    }
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }




}


