package entity;
// Generated 27-05-2017 13:33:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Editorial generated by hbm2java
 */
public class Editorial  implements java.io.Serializable {


     private int idEditorial;
     private String nombreEditorial;
     private Set documentos = new HashSet(0);

    public Editorial() {
    }

	
    public Editorial(int idEditorial, String nombreEditorial) {
        this.idEditorial = idEditorial;
        this.nombreEditorial = nombreEditorial;
    }
    public Editorial(int idEditorial, String nombreEditorial, Set documentos) {
       this.idEditorial = idEditorial;
       this.nombreEditorial = nombreEditorial;
       this.documentos = documentos;
    }
   
    public int getIdEditorial() {
        return this.idEditorial;
    }
    
    public void setIdEditorial(int idEditorial) {
        this.idEditorial = idEditorial;
    }
    public String getNombreEditorial() {
        return this.nombreEditorial;
    }
    
    public void setNombreEditorial(String nombreEditorial) {
        this.nombreEditorial = nombreEditorial;
    }
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }




}


