package entity;
// Generated 27-05-2017 13:33:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ejemplar generated by hbm2java
 */
public class Ejemplar  implements java.io.Serializable {
  
     private int id_ejemplar;
     private EjemplarId id;
     private Estado estado;
     private Ubicacion ubicacion;
     private Documento documento;
     private Set solicitudPrestamos = new HashSet(0);
     private Set prestamos = new HashSet(0);
     private Set reservas = new HashSet(0);

    public Ejemplar() {
    }

	
    public Ejemplar(Estado estado, Ubicacion ubicacion, Documento documento) {
        this.estado = estado;
        this.ubicacion = ubicacion;
        this.documento = documento;
    }
    
     public Ejemplar(int id_ejemplar, Estado estado, Ubicacion ubicacion, Documento documento) {
        this.id_ejemplar = id_ejemplar;
        this.estado = estado;
        this.ubicacion = ubicacion;
        this.documento = documento;
    }
    
    public Ejemplar( Estado estado, Ubicacion ubicacion, Documento documento, Set solicitudPrestamos, Set prestamos, Set reservas) {
       this.estado = estado;
       this.ubicacion = ubicacion;
       this.documento = documento;
       this.solicitudPrestamos = solicitudPrestamos;
       this.prestamos = prestamos;
       this.reservas = reservas;
    }
   
    public int getId_ejemplar() {
        return id_ejemplar;
    }

    public void setId_ejemplar(int id_ejemplar) {
        this.id_ejemplar = id_ejemplar;
    }
    
    public EjemplarId getId() {
        return this.id;
    }
    
    public void setId(EjemplarId id) {
        this.id = id;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Documento getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Documento documento) {
        this.documento = documento;
    }
    public Set getSolicitudPrestamos() {
        return this.solicitudPrestamos;
    }
    
    public void setSolicitudPrestamos(Set solicitudPrestamos) {
        this.solicitudPrestamos = solicitudPrestamos;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


