package entity;
// Generated 27-05-2017 13:33:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region  implements java.io.Serializable {


     private long idRegion;
     private String nombreRegion;
     private String ordinalRegion;
     private Set comunas = new HashSet(0);

    public Region() {
    }

	
    public Region(long idRegion, String nombreRegion, String ordinalRegion) {
        this.idRegion = idRegion;
        this.nombreRegion = nombreRegion;
        this.ordinalRegion = ordinalRegion;
    }
    public Region(long idRegion, String nombreRegion, String ordinalRegion, Set comunas) {
       this.idRegion = idRegion;
       this.nombreRegion = nombreRegion;
       this.ordinalRegion = ordinalRegion;
       this.comunas = comunas;
    }
   
    public long getIdRegion() {
        return this.idRegion;
    }
    
    public void setIdRegion(long idRegion) {
        this.idRegion = idRegion;
    }
    public String getNombreRegion() {
        return this.nombreRegion;
    }
    
    public void setNombreRegion(String nombreRegion) {
        this.nombreRegion = nombreRegion;
    }
    public String getOrdinalRegion() {
        return this.ordinalRegion;
    }
    
    public void setOrdinalRegion(String ordinalRegion) {
        this.ordinalRegion = ordinalRegion;
    }
    public Set getComunas() {
        return this.comunas;
    }
    
    public void setComunas(Set comunas) {
        this.comunas = comunas;
    }




}


