package entity;
// Generated 27-05-2017 13:33:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private int idReserva;
     private Ejemplar ejemplar;
     private Usuario usuario;
     private Date fechaReserva;

    public Reserva() {
    }

    public Reserva(int idReserva, Ejemplar ejemplar, Usuario usuario, Date fechaReserva) {
       this.idReserva = idReserva;
       this.ejemplar = ejemplar;
       this.usuario = usuario;
       this.fechaReserva = fechaReserva;
    }
   
    public int getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(int idReserva) {
        this.idReserva = idReserva;
    }
    public Ejemplar getEjemplar() {
        return this.ejemplar;
    }
    
    public void setEjemplar(Ejemplar ejemplar) {
        this.ejemplar = ejemplar;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaReserva() {
        return this.fechaReserva;
    }
    
    public void setFechaReserva(Date fechaReserva) {
        this.fechaReserva = fechaReserva;
    }




}


