package entity;
// Generated 27-05-2017 13:33:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private int idPrestamo;
     private Prestamo prestamo;
     private Date horaDevolucion;

    public Sala() {
    }

    public Sala(Prestamo prestamo, Date horaDevolucion) {
       this.prestamo = prestamo;
       this.horaDevolucion = horaDevolucion;
    }
   
    public int getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(int idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Prestamo getPrestamo() {
        return this.prestamo;
    }
    
    public void setPrestamo(Prestamo prestamo) {
        this.prestamo = prestamo;
    }
    public Date getHoraDevolucion() {
        return this.horaDevolucion;
    }
    
    public void setHoraDevolucion(Date horaDevolucion) {
        this.horaDevolucion = horaDevolucion;
    }




}


