package entity;
// Generated 27-05-2017 13:33:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SolicitudPrestamo generated by hbm2java
 */
public class SolicitudPrestamo  implements java.io.Serializable {


     private int idSolicitud;
     private Ejemplar ejemplar;
     private Usuario usuario;
     private Date horaSolicitud;

    public SolicitudPrestamo() {
    }

    public SolicitudPrestamo(int idSolicitud, Ejemplar ejemplar, Usuario usuario, Date horaSolicitud) {
       this.idSolicitud = idSolicitud;
       this.ejemplar = ejemplar;
       this.usuario = usuario;
       this.horaSolicitud = horaSolicitud;
    }
   
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Ejemplar getEjemplar() {
        return this.ejemplar;
    }
    
    public void setEjemplar(Ejemplar ejemplar) {
        this.ejemplar = ejemplar;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getHoraSolicitud() {
        return this.horaSolicitud;
    }
    
    public void setHoraSolicitud(Date horaSolicitud) {
        this.horaSolicitud = horaSolicitud;
    }




}


