package entity;
// Generated 27-05-2017 13:33:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubicacion generated by hbm2java
 */
public class Ubicacion  implements java.io.Serializable {


     private int idUbicacion;
     private String nombreUbic;
     private Set ejemplars = new HashSet(0);

    public Ubicacion() {
    }

	
    public Ubicacion(int idUbicacion, String nombreUbic) {
        this.idUbicacion = idUbicacion;
        this.nombreUbic = nombreUbic;
    }
    public Ubicacion(int idUbicacion, String nombreUbic, Set ejemplars) {
       this.idUbicacion = idUbicacion;
       this.nombreUbic = nombreUbic;
       this.ejemplars = ejemplars;
    }
   
    public int getIdUbicacion() {
        return this.idUbicacion;
    }
    
    public void setIdUbicacion(int idUbicacion) {
        this.idUbicacion = idUbicacion;
    }
    public String getNombreUbic() {
        return this.nombreUbic;
    }
    
    public void setNombreUbic(String nombreUbic) {
        this.nombreUbic = nombreUbic;
    }
    public Set getEjemplars() {
        return this.ejemplars;
    }
    
    public void setEjemplars(Set ejemplars) {
        this.ejemplars = ejemplars;
    }




}


