package entity;
// Generated 27-05-2017 13:33:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Rol rol;
     private Comuna comuna;
     private String rut;
     private String usr;
     private String contrasena;
     private String nombrePrimer;
     private String nombreSegundo;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String correo;
     private int telefono;
     private String direccion;
     private char activado;
     private Set reservas = new HashSet(0);
     private Set solicitudPrestamos = new HashSet(0);
     private Set prestamos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, Rol rol, Comuna comuna, String rut, String usr, String contrasena, String nombrePrimer, String nombreSegundo, String apellidoPaterno, String apellidoMaterno, String correo, int telefono, String direccion, char activado) {
        this.idUsuario = idUsuario;
        this.rol = rol;
        this.comuna = comuna;
        this.rut = rut;
        this.usr = usr;
        this.contrasena = contrasena;
        this.nombrePrimer = nombrePrimer;
        this.nombreSegundo = nombreSegundo;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.correo = correo;
        this.telefono = telefono;
        this.direccion = direccion;
        this.activado = activado;
    }
    public Usuario(int idUsuario, Rol rol, Comuna comuna, String rut, String usr, String contrasena, String nombrePrimer, String nombreSegundo, String apellidoPaterno, String apellidoMaterno, String correo, int telefono, String direccion, char activado, Set reservas, Set solicitudPrestamos, Set prestamos) {
       this.idUsuario = idUsuario;
       this.rol = rol;
       this.comuna = comuna;
       this.rut = rut;
       this.usr = usr;
       this.contrasena = contrasena;
       this.nombrePrimer = nombrePrimer;
       this.nombreSegundo = nombreSegundo;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.correo = correo;
       this.telefono = telefono;
       this.direccion = direccion;
       this.activado = activado;
       this.reservas = reservas;
       this.solicitudPrestamos = solicitudPrestamos;
       this.prestamos = prestamos;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Comuna getComuna() {
        return this.comuna;
    }
    
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getUsr() {
        return this.usr;
    }
    
    public void setUsr(String usr) {
        this.usr = usr;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getNombrePrimer() {
        return this.nombrePrimer;
    }
    
    public void setNombrePrimer(String nombrePrimer) {
        this.nombrePrimer = nombrePrimer;
    }
    public String getNombreSegundo() {
        return this.nombreSegundo;
    }
    
    public void setNombreSegundo(String nombreSegundo) {
        this.nombreSegundo = nombreSegundo;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public char getActivado() {
        return this.activado;
    }
    
    public void setActivado(char activado) {
        this.activado = activado;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }
    public Set getSolicitudPrestamos() {
        return this.solicitudPrestamos;
    }
    
    public void setSolicitudPrestamos(Set solicitudPrestamos) {
        this.solicitudPrestamos = solicitudPrestamos;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }




}


